Sprint 2
HereHaveTheseFlowers/middle.messenger.praktikum.yandex pull request #2
Opened 2022-09-11 21:10 UTC by HereHaveTheseFlowers

Здравствуйте! Отправляю готовый наполовину проект, потому что дедлайн прошел и я хотел бы получить фидбек на то, правильно ли делаю компонентный подход. Спасибо.

Сделаны пункты:
- [x] Внедрите TypeScript.
- [x] Сделайте страницу со списком чатов и лентой переписки. Не забудьте, что поле ввода сообщения должно называться message.
- [x] Добавьте компонентный подход в проект:
- [x] Используйте реализацию блока и Event Bus;
- [x] Разделите проект на папки с компонентами и страницами (components и blocks или pages).
- [x] Генерация страниц должна происходить на стороне клиента;
- [x] Сборка должна быть при помощи Parcel;
- [x] Структурируйте проект в соответствии с советами по архитектуре:
- [ ] Добавьте класс для работы с запросами
- [ ] Сделайте сбор данных из формы.
- [ ] Добавьте валидацию на все формы.
- [ ] Добавьте ESLint:
- [ ] Добавьте Stylelint.

2022-09-12 18:23 UTC, agadoev requested changes
Привет, спасибо за работу
Интересный дизайн у тебя)
Я посмотрел код и кажется еще есть над чем поработать. Компонентный подход в целом норм, но я написал предложение по улучшению ниже. Так же заметил, что можно улучшить использование TS'а.
1.  Старайся поменьше использовать any. Почти наверняка есть способ, как избежать использование этого типа
2. Касаемо компонентного подхода. Меня сначала ввело в заблуждение названия auth_row и options_row, но потом я понял почему ты так сделал. Такой подход возможен, но тогда я не хранил бы эти компоненты в отдельной папке компонентов, а положил бы их в папки со страницами, в которых они используются. Получится некая иерархия. Так правильнее сделать еще и потому, что помимо этих страниц они нигде использоваться не будут, а значит по смыслу должны находиться в папке со страницей
3. Постарайся, пожалуйста, привести код в проекте к единому стилю. В основном это касается нейминга, как переменных и свойств, так и файлов

Ну и все таки придется доделать валидацию, без нее не приму :)
Жду правок и двинемся дальше

2022-09-12 18:23 UTC, agadoev commented on src/components/auth_row/index.ts
> +    type: string;
Полагаю, что type может принимать ограниченное количество значений. Если это так, то лучше ограничить тип, используя discriminated union 
```suggestion
    type: 'type1' | 'type2' и тд;
```

2022-09-12 18:23 UTC, agadoev commented on src/components/auth_row/index.ts
> +        }
Смотри, тут три if'а, один из которых вложенный. Представь, что тебе надо будет дебажить этот код и каждый раз держать в голове, что у тебя есть if'ы. Это довольно сложно и этот кусок кода можно упростить

```suggestion
        if (!this.element) {
            return
        }

        this.element.classList.add("auth_field", props.div_class || '');
```

2022-09-12 18:23 UTC, agadoev commented on src/components/button/index.ts
> +  }
Этот клубок из if-ов неплохо бы распутать. По аналогии с тем, как я предложил это сделать в auth_row. Сейчас у этого кода довольно высокая [цикломатическая сложность](https://docs.microsoft.com/ru-ru/dotnet/fundamentals/code-analysis/quality-rules/ca1502)

2022-09-12 18:23 UTC, agadoev commented on src/components/button/index.ts
> +  added_class?: string | Array<string>;
Я бы оставил только Array<string>, и при чтении из этого свойства использовал бы spread operator

2022-09-12 18:23 UTC, agadoev commented on src/components/auth_row/auth_row.hbs
> +<input name="{{name}}" type="{{type}}" class="auth__input" placeholder="{{placeholder}}">
Название auth_row немного сбивает с толку и я, например, не сразу понял, о чем этот компонент, пока не поискал его использование в коде. Советую переименовать

2022-09-12 18:23 UTC, agadoev commented on src/pages/login/login.ts
> +                            {div_class: "", name: "password", type: "password", placeholder: "Password"} ]
1. Точно стоит поправить форматирование. Сейчас сложно воспринимать информацию
2. Почему object? это не сильно отличается от any. К тому же есть тип AuthProps
```suggestion
export const authrows: Array<AuthProps> = [ {div_class: "", name: "login", type: "text", placeholder: "Login"}, 
                            {div_class: "", name: "password", type: "password", placeholder: "Password"} ]
```

2022-09-12 18:23 UTC, agadoev commented on src/pages/login/login.ts
> +    authrows: Array<object>;
```suggestion
    authrows: Array<AuthProps>;
```

2022-09-12 18:23 UTC, agadoev commented on src/pages/error/error.ts
> +    errorbutton: Button;
давай использовать единый стиль нейминга в проекте. Сейчас я вижу три
1. camelCase
2. snake_case
3. слитоноенаписание

выбери любой из них, важно, чтобы везде в проекте использовался только один стиль, иначе проект быстро захламится

2022-09-12 18:23 UTC, agadoev commented on src/pages/chats/chats.ts
> +export const chats: Array<object> = [  { name: "Andrey",     lastmessage: "Image",   lastmessagedate: "10:49", newmessages: "2" },
```suggestion
export const chats: Array<ChatProps> = [  { name: "Andrey",     lastmessage: "Image",   lastmessagedate: "10:49", newmessages: "2" }, 
```

2022-09-12 18:23 UTC, agadoev commented on src/utils/Block.ts
> +class Block<P extends Record<string, any> = any> {
тут можно избежать использования any
```suggestion
class Block<P extends Record<string, unknown> = Record<string, never>> {
```
таким образом мы указываем дефолтное значение для типа пропсов, чтобы не указывать пропсы в тех компонентах, в которых их нет (как например в Mainlogo)

2022-09-12 18:23 UTC, agadoev commented on src/utils/Block.ts
> +  public childrenCollection: Array<any>;
Не очень понятно в чем разница между children и childrenCollection

2022-09-12 18:23 UTC, agadoev commented on src/components/mainlogo/index.ts
> +        super('div', props);
Block не может быть пропсом. Вообще если для этого компонента не нужны пропсы, то просто не указывай их. Я написал комментарий как изменить Block.ts чтобы этого можно было добиться

2022-09-12 18:23 UTC, agadoev commented on src/utils/Block.ts
> +    const { props, children } = this._getChildrenAndProps(propsWithChildren);
И здесь еще подправим, чтобы можно было не указывать пропсы там, где они не нужны
```suggestion
  constructor(tagName = "div", propsWithChildren = {}) {
    const eventBus = new EventBus();

    const { props, children } = this._getChildrenAndProps(propsWithChildren as P);
```

2022-09-12 18:23 UTC, agadoev commented on tsconfig.json
> +    "noImplicitAny": true,
Странно, что noImplicitAny стоит true, но any все равно используется. Не стоит игнорировать подсказы TS'a.
Я бы еще добавил сюда полезную настройку noImplicitReturns: true

2022-09-12 18:23 UTC, agadoev commented on src/pages/options/options.ts
> +                  }
Точно ли тут нужно использовать вложенные setTimeout'ы? Пока что выглядит как костыль. Мне сложно понять, что должен делать этот код, поэтому я не могу предложить вариант рефакторинга, но советую подумать как распутать этот клубок

2022-09-12 18:23 UTC, agadoev commented on src/pages/options/options.ts
> +                    for(const profile of document.querySelectorAll<HTMLElement>('.options__profile'))
крутая идея использовать generic'и вместо явного приведения типов!

2022-09-12 18:23 UTC, agadoev commented on src/pages/options/options.ts
> +                                                        { input: "true", attr_first: "New Password (Again)", name: "newPassword", type: "password", placeholder: "•••••••••••"  }]
Я заметил, что в коде довольно много таких заглушек. Все таки данные не совсем относятся к исходному коду и хранить их в одном файле как-то неправильно. Предлагаю вынести их в json'ы.

2022-09-15 06:54 UTC, HereHaveTheseFlowers commented
Привет @agadoev , спасибо огромное за ревью, ты всё написал по делу и я узнал для себя новое!

Постарался исправить все недочеты, трудности возникли лишь с несколькими, пунктами:
 - заглушки в отдельные json убирать не стал, потому что понял, что там в будущем будут events, которые будут являться объектами, а объекты пихать в json очень очень неудобно. Но ты прав, выглядит это не очень, поэтому я сделал все заглушки отдельными намного более читабельными файлами. inputsList.ts, к примеру.
 
 - class Block<P extends Record<string, unknown> = Record<string, never>>  здесь убрать any не получилось, тайпскрипт ругается сильно, и я долго пытался разобраться, почему, но не смог(
 
 В итоге, все остальное я поправил, auth_row убрал и вместо него сделал компонент input, который используется по всему проекту. optionsRow убрал в страничку options, потому что используется он только там, а еще он теперь тоже использует input. chat убрал в chatsPage. Решил использовать camelCase)
 
 Валидация готова и работает, она выполняется как в Input'ах, так и при сабмите форм (validate.ts и setupForm.ts). При сабмитте данные выводятся в логи в виде объекта (если они прошли валидацию, конечно же.) Валидацию старался делать строго по тз.
 Реализация fetchWithRetry тоже присутствует, на самом деле просто взял ту, что делал в тренажере, и типизировал.

2022-09-16 07:45 UTC, agadoev approved these changes
Привет, @HereHaveTheseFlowers 
Спасибо за правки, код действительно стал лучше. Касаемо заглушек - твое решение вполне нормальное.
Могу посоветовать две книги, которые точно забустят твои навыки написания кода - "Чистый код" и "Чистая архитектура" Роберта Мартина.


В целом все ок, все задания выполнены, я работу принимаю. Удачи в следующем спринте :)

2022-09-16 17:14 UTC, HereHaveTheseFlowers commented
Спасибо большое, жаль даже что наверное не ты будешь проверять мой следующий спринт

2022-09-16 17:14 UTC, merged